create table if not exists companies (
  id bigint generated by default as identity primary key,

  name text,
  domain text,
  career_url text not null unique,

  discovery_source text not null default 'manual',
  discovered_at timestamptz default now(),

  ats text,
  ats_board_name text,
  ats_url text,

  created_at timestamptz default now(),
  updated_at timestamptz default now()
);