CREATE TABLE IF NOT EXISTS public.applications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  job_posting_id bigint NOT NULL,

  -- Logical references into the separate CRM database.
  -- These are intentionally NOT PostgreSQL foreign keys.
  crm_lead_id integer NULL,
  crm_quiz_id text NULL,

  status text NOT NULL DEFAULT 'applied',

  applied_at timestamptz NOT NULL DEFAULT now(),

  application_url text NULL,
  resume_version text NULL,
  notes text NULL,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT applications_job_posting_id_fkey
    FOREIGN KEY (job_posting_id)
    REFERENCES public.job_postings(id)
    ON DELETE CASCADE,

  CONSTRAINT applications_status_check
    CHECK (
      status IN (
        'applied',
        'interview',
        'offer',
        'rejected'
      )
    ),

  CONSTRAINT applications_one_per_job
    UNIQUE (job_posting_id)
);

CREATE INDEX IF NOT EXISTS idx_applications_job_posting_id
  ON public.applications(job_posting_id);

CREATE INDEX IF NOT EXISTS idx_applications_crm_lead_id
  ON public.applications(crm_lead_id);

CREATE INDEX IF NOT EXISTS idx_applications_status
  ON public.applications(status);

CREATE INDEX IF NOT EXISTS idx_applications_applied_at
  ON public.applications(applied_at);