-- ============================================================
-- Application Contacts
--
-- An application can have many CRM contacts.
--
-- The CRM database is separate from the job-search database,
-- so crm_lead_id is a logical reference only.
-- ============================================================

CREATE TABLE IF NOT EXISTS public.application_contacts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  application_id bigint NOT NULL,

  crm_lead_id integer NOT NULL,

  crm_quiz_id text NULL,

  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT application_contacts_application_fkey
    FOREIGN KEY (application_id)
    REFERENCES public.applications(id)
    ON DELETE CASCADE,

  CONSTRAINT application_contacts_unique
    UNIQUE (
      application_id,
      crm_lead_id
    )
);


-- ============================================================
-- Indexes
-- ============================================================

CREATE INDEX IF NOT EXISTS
  idx_application_contacts_application_id
ON public.application_contacts (
  application_id
);

CREATE INDEX IF NOT EXISTS
  idx_application_contacts_crm_lead_id
ON public.application_contacts (
  crm_lead_id
);


-- ============================================================
-- Migrate existing single-contact applications
--
-- Existing applications currently have:
--
--   applications.crm_lead_id
--   applications.crm_quiz_id
--
-- Copy those into the new many-to-many table.
--
-- Applications with no CRM contact are ignored.
-- ============================================================

INSERT INTO public.application_contacts (
  application_id,
  crm_lead_id,
  crm_quiz_id
)
SELECT
  a.id,
  a.crm_lead_id,
  a.crm_quiz_id
FROM public.applications a
WHERE a.crm_lead_id IS NOT NULL
ON CONFLICT (
  application_id,
  crm_lead_id
)
DO NOTHING;